Goalie MergeSCurve
KgpKubs/robocup pull request #43
Opened 2019-02-09 13:34 UTC by thebhatman

Goalie on MergeSCurve added. Need to improve it so that it can intercept the moving ball and guard the goal.

2019-02-09 19:20 UTC, saurabhkgp21 commented
@thebhatman  U had used old `node_class.cpp` for changing default position of bots and hence you had undone changes made by shamin to remove unwanted variables in beliefstate.
Just pull updated node_class.cpp and do changes for updating default positions.

2019-02-09 19:20 UTC, saurabhkgp21 requested changes

2019-02-09 19:20 UTC, saurabhkgp21 commented on belief_state/src/node.cpp
> +  ros::init(argc, argv, "beliefstate_node1");
@thebhatman Why this change?

2019-02-09 20:46 UTC, thebhatman commented
> @thebhatman U had used old `node_class.cpp` for changing default position of bots and hence you had undone changes made by shamin to remove unwanted variables in beliefstate.
> Just pull updated node_class.cpp and do changes for updating default positions.

Oh Okay! My bad. Sure! Will do that.

2019-02-10 12:43 UTC, thebhatman commented
Belief state unwanted variables removed. Node name back to usual. Default bot positions updated so that they do not interfere with playing half field.

2019-02-10 12:45 UTC, saurabhkgp21 commented
@thebhatman no changes are showing in beliefstate now

2019-02-10 12:45 UTC, saurabhkgp21 approved these changes

2019-03-02 19:53 UTC, merged